language: generic
sudo: required
service:
  - docker

before_install:
  - docker builder -t zhanxu1031/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zhanxu1031/docker-react npm run test