sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zhanxu1031/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zhanxu1031/docker-react npm run test